baseURL = 'https://jordanemme.com/'
languageCode = 'en-us'
title = "Jordan Emme's Blog"
author = "Jordan Emme"

  [params]
    subtitle = 'A blog of maths and computer science ramblings'

    [params.theme_config]
      appearance = "auto"
      back_home_text = ".."
      date_format = "2006-01-02"
      isListGroupByDate = false
  
  
  [module]
    [module.hugoVersion]
      extended=true
      min = "0.41.0"
  
  [markup]
    [markup.goldmark]
      [markup.goldmark.parser]
        [markup.goldmark.parser.attribute]
          block = true
          title = true
    [markup.highlight]
      anchorLineNos = false
      codeFences = true
      guessSyntax = false
      hl_Lines = ''
      hl_inline = false
      lineAnchors = ''
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = true
      noClasses = true
      noHl = false
      style = 'rrt'
      tabWidth = 4
    [markup.tableOfContents]
      startLevel = 2
      endLevel = 3
      ordered = false
